name: Pull Request

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '00 15 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Set yesterday date as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "YEAR=`date "+%Y"`" >> $GITHUB_ENV
          echo "MONTH=`date "+%m"`" >> $GITHUB_ENV
          echo "DAY=`date --date "-1 days" "+%d"`" >> $GITHUB_ENV
          echo "PR_TITLE=\"Add: Daily of $YEAR-$MONTH-$DAY\"" >> $GITHUB_ENV
      - name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }} || true
          git switch daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
          docker-compose build
          docker-compose up -d
          docker-compose exec -T blog.momee.mt bash -c "cd uni && nimble build && cd ../ && git branch && ./uni/bin/uni check:daily"
          gh pr create -B main -t ${{ env.PR_TITLE }} -b ""
